name: Build AS COIN APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create Android project files
        run: |
          flutter create --platforms=android --org com.ascoin .

      - name: Get dependencies
        run: flutter pub get

      - name: Show Android SHA-1
        run: |
          keytool -list -v \
            -keystore "$HOME/.android/debug.keystore" \
            -alias androiddebugkey \
            -storepass android \
            -keypass android | grep "SHA1:"

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AS-COIN-Android
          path: build/app/outputs/flutter-apk/app-release.apk
